### ISSUE TITLE
Build error for QT 6.2

### ISSUE THREAD

**Issue by michallenc** [silicon-heaven/shvapp#3]
Shvapp build results in following error:

```
/home/michal/Michal/GIT/silicon-heaven/shvapp/historyprovider3/src/shvjournalnode.cpp: In lambda function:
/home/michal/Michal/GIT/silicon-heaven/shvapp/historyprovider3/src/shvjournalnode.cpp:512:43: error: ‘whenAll’ is not a member of ‘QtFuture’
  512 |                                 QtFuture::whenAll(all_files_synced.begin(), all_files_synced.end()).then([promise = std::move(promise)] (const auto&) mutable {
      |                                           ^~~~~~~
/home/michal/Michal/GIT/silicon-heaven/shvapp/historyprovider3/src/shvjournalnode.cpp:586:35: error: ‘whenAll’ is not a member of ‘QtFuture’
  586 |                         QtFuture::whenAll(all_files_synced.begin(), all_files_synced.end()).then([this, slave_hp_path, cache_dir_path, file_list, promise = std::move(promise)] (const auto&) mutable {
      |                                   ^~~~~~~
/home/michal/Michal/GIT/silicon-heaven/shvapp/historyprovider3/src/shvjournalnode.cpp: In member function ‘void FileSyncer::syncFiles()’:
/home/michal/Michal/GIT/silicon-heaven/shvapp/historyprovider3/src/shvjournalnode.cpp:657:35: error: ‘whenAll’ is not a member of ‘QtFuture’
  657 |                         QtFuture::whenAll(all_synced.begin(), all_synced.end()).then([this] (const auto&) {
      |  
```

This is caused by `QtFuture::whenAll` being added in QT 6.3. Is shvspy supposed to be backported to QT 6.2 (used in Ubuntu 22.04 long term version) and this is an error or is update to newer QT (and thus to Ubuntu version) the only (or preferable) option?

**Comment by michallenc** [comment]
This may not be the only QT 6.2 related build error as the compilation is stopped after this one. It may also affect shvspy.

**Comment by fvacek** [comment]
@syyyr can you please take a look on it?

**Comment by michallenc** [comment]
Regarding shvspy: There is just one build error caused by `QCryptographicHash::addData`, similar to this [PR to libshv](https://github.com/silicon-heaven/libshv/pull/290). I will create fix pull request for shvspy tomorrow.

**Comment by syyyr** [comment]
I'd say it's always preferable to update your Qt version, but I think shv should be buildable with 6.2.0. For now, I've just increased the needed version for HP3 to 6.3.0 (i created an MR on our Gitlab for that @fvacek). Is HP3 important to you with 6.2.0? It's not a trivial port, but I suppose I could be done.

**Comment by michallenc** [comment]
@syyyr HP3 is not important at all for me, I just use shvbroker from shvapp library which builds without errors after the fixes in libshv.

**Comment by syyyr** [comment]
Alright then :) I'll look into shvspy too.

**Comment by michallenc** [comment]
This PR https://github.com/silicon-heaven/shvspy/pull/26 should fix the shvspy build.

**Comment by fvacek** [comment]
merged

**Comment by syyyr** [comment]
I think this can be closed?

**Comment by michallenc** [comment]
> I think this can be closed?

I think so.
